### ISSUE TITLE
Support for skins format 1.8

### ISSUE THREAD

**Issue by bell07** [jordan4ibanez/newhand#14]
Please add support for skins in 1.8 format. Currently the hand looks strange with such skin.

The compatible player model you find in https://github.com/minetest-mods/skinsdb/tree/master/models or https://github.com/stujones11/minetest-models/tree/master/character/3d_armor/mt_0.5.0-dev/multiskin_branch

The compatible skins you can get from https://minecraft.novaskin.me/

**Comment by jordan4ibanez** [comment]
Your skins addition has been integrated into the main branch, thank you

**Comment by bell07** [comment]
This issue was about support in 1.8 format, that is not solved yet. Pls. repoen the issue

**Comment by jordan4ibanez** [comment]
I would recommend you make a fork because I'm never going to touch this repo again

**Comment by bell07** [comment]
I integrated the newhand already into skindsb [function skin_class:set_hand_from_texture()](https://github.com/minetest-mods/skinsdb/blob/master/skin_meta_api.lua#L59)

Maybe you can directly contribute into skinsdb? The requirement is to remove the [if skin_format == "1.0" then ](https://github.com/minetest-mods/skinsdb/blob/master/skinlist.lua#L54) line.

Skinsdb supports 1.8-er skins with provided skinsdb_3d_armor_character model in https://github.com/minetest-mods/skinsdb/tree/master/models, but the provided hand model does support 1.0 only.
