### ISSUE TITLE
Skin changer

### ISSUE THREAD

**Issue by masrourmouad** [jordan4ibanez/newhand#3]
Hi Jordan, thank you for your work in this mod, i know that i'm you asking a lot, but can you make a skin changer that works in conjunction with this mod, thank you alot :)

**Comment by jordan4ibanez** [comment]
You can now use tenplus1's skins plus mod!

**Comment by jordan4ibanez** [comment]
But making a new skin changer mod is actually a very good idea, I'll leave this open until I make progress with that

**Comment by masrourmouad** [comment]
thank you
